version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  identity.api:
    image: microservices/identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sql.data