version: '3.4'

services:
  RabbitMQ:
    image: "rabbitmq:3-management"
    hostname: "RabbitMQ"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "RabbitMQ"
    #volumes:
      #- "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"

  # MySQL
  mysql.data: 
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
    - "3306:3306"
    - "33060:33060"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: IdentityAPI

  # PostgreSQL
  postgre.data:
    image: postgres:10.5
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

  # UserLoginLogsAPI
  userlogs.api:
    image: microservices/userslogapi
    build:
      context: .
      dockerfile: src/Services/UserAuditLogs/WAL.UserLoginLogs.API/Dockerfile
    depends_on:
      - postgre.data

  # IdentityAPI
  identity.api:
    image: microservices/identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/WAL.Identity.API/Dockerfile
    depends_on:
      - mysql.data

volumes:
  mysql_data:
  postgre_data: